//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Selu383Bot.GithubWebhook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Selu383Bot.GithubWebhook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Enter your email&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Provde your email for azure&lt;/h1&gt;
        ///    &lt;p&gt;I&apos;m lazy and don&apos;t want to type your emails - enter whatever email azure should invite you with&lt;/p&gt;
        ///    &lt;p&gt;Don&apos;t mess up&lt;/p&gt;
        ///    &lt;form method=&quot;post&quot;
        ///          onSubmit=&quot;document.getElementById(&apos;submit&apos;).disabled=true;&quot;
        ///          style=&quot;display: flex; gap: 40px; flex-direction: column; max-width: 300px&quot;&gt;
        ///        &lt;div style=&quot;display: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SetEmailAddress {
            get {
                return ResourceManager.GetString("SetEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Provide Expo Secret&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Provide your expo token as a secret&lt;/h1&gt;
        ///    &lt;p&gt;You&apos;d normally be able to specify secrets yourself in github, but as a student you are a bit more limited&lt;/p&gt;
        ///    &lt;p&gt;Specify your expo token your target repository&lt;/p&gt;
        ///    &lt;p&gt;You can do this many times - the last one you submit &apos;wins&apos;&lt;/p&gt;
        ///    &lt;form method=&quot;post&quot;
        ///          onSubmit=&quot;document.getElementById(&apos;submit&apos;).disabl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SetExpoSecret {
            get {
                return ResourceManager.GetString("SetExpoSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Provide Publish Profile&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Provide your publish profile as a secret&lt;/h1&gt;
        ///    &lt;p&gt;You&apos;d normally be able to specify secrets yourself in github, but as a student you are a bit more limited&lt;/p&gt;
        ///    &lt;p&gt;Upload your file and your target repository&lt;/p&gt;
        ///    &lt;p&gt;You can do this many times - the last one you submit &apos;wins&apos;&lt;/p&gt;
        ///    &lt;form method=&quot;post&quot;
        ///          onSubmit=&quot;document.getElementById(&apos;submit&apos;). [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SetPublishProfile {
            get {
                return ResourceManager.GetString("SetPublishProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Enter webhook URL&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Provde a URL that will be called with each GitHub webhook call&lt;/h1&gt;
        ///    &lt;p&gt;Each group/repository can have only one of these at a time - the last one entered &apos;wins&apos;.&lt;/p&gt;
        ///    &lt;form method=&quot;post&quot;
        ///          onSubmit=&quot;document.getElementById(&apos;submit&apos;).disabled=true;&quot;
        ///          style=&quot;display: flex; gap: 40px; flex-direction: column; max-width: 300px&quot;&gt;
        ///        &lt;div style=&quot;disp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SetWebHook {
            get {
                return ResourceManager.GetString("SetWebHook", resourceCulture);
            }
        }
    }
}
